### ISSUE TITLE
fair game options

### ISSUE THREAD

**Issue by onyiny-ang** [oldterns/VileBot#58]
Jeopardy and omgword are definitely biased to reward those with particular language and cultural understandings.
Lottery and/or another game would hopefully level the playing field. Lottery, at least, should be fairly straight forward to implement.

**Comment by itpun** [comment]
I don't think it would be a difficult feature to write, but I don't know if its a good idea to continue adding more gambling features to this. You could argue that jeopardy is theoritically still "gambling" (you lose karma if you guess wrong), but on the surface its not intended so. The only game of chance we have at the moment is !roll , so Im going to have to have a vote on whether we should include more or that or not

**Comment by onyiny-ang** [comment]
I'm not really arguing in favour of gambling options per se, simply games besides jeopardy/omgword that are accessible to more people and don't presuppose being born/raised in and/or obsessed with North America/English. It doesn't have to be completely devoid of some kind of skill, though on a text based platform, I'm not sure exactly what to suggest that would fit the bill.

**Comment by emmettu** [comment]
There's a great British game show called _Countdown_ that features a game where contestants choose a total of 6 numbers (either large (25, 50, 75, 100)), or small (1-10). A random number is then generated (between 100 and 1000 I think) and contestants must use the 6 numbers (you can leave out numbers but you can not use a number twice), by adding/subtracting/multiplying/dividing them to get the randomly generated number (or as close as possible).

Example:

The command to start a game would be something like: 
```
2 large 4 small
``` 
the contestant is asking for 2 large numbers and 4 small numbers.

Numbers would be generated:
```
Your numbers are: 25, 50, 9, 6, 4, 3, 5
```

Then the target number would be generated:

```
The target is: 456
```

Then contestants would write out some equation to get as close as possible to the target before the time is up.

```
(((5 - 3) * 50) * 4) + (9 * 6)
```

The result of this equation is 454 which is 2 off. So if that was the closest this contestant would get 8 points via the formula: score = (10 - distance away from answer) (no negative scores, just 0).

I mean technically this wouldn't be fair because it would cater to contestants who are good at Math, but I don't think VileBot will ever be able to achieve Karma game fairness anyway. I just think it would be a fun game.

**Comment by amisevsk** [comment]
Oh man, countdown is a great idea @emmettu! The main challenge would be figuring out how to generate a target number, some of those answers are pretty dang ridiculous.

**Comment by emmettu** [comment]
@amisevsk I think the show actually uses a random number as sometimes the math whizz on the show Rachel Riley admits there is no perfect answer, and the contestants just need to get as close as possible. The vast majority of cases though have multiple correct answers so I think generating a random number is the way to go.

Writing an expression parser would be a biiiit tricky IMO (it would need to make sure numbers aren't being used more than once), but not too hard.

**Comment by onyiny-ang** [comment]
@emmettu This is a great idea! I don't think it's reasonable to aim for something perfectly fair in every way,  but diversifying the skills someone needs gain karma would definitely help :)

**Comment by itpun** [comment]
@emmettu thanks for the idea! It doesn't seem like a too difficult of a task to do... only thing would be the target number would need some tweaking in the beginning probably until we can get something more reliable but still interesting

**Comment by emmettu** [comment]
@itpun from my experience watching Countdown nothing special needs to be done to generate interesting target numbers, a random number between 100 and 1000 always works just fine (sometimes the closest answer is 1 or 2 away) but 95% of the time you can get to the target from any set of 6 numbers.

**Comment by itpun** [comment]
Before I forget, I think it would be cool to have submissions be private as well. So instead of doing !solution <answer> , it would probably be better to give the contestant the option to direct message the submission as well.

**Comment by emmettu** [comment]
If the solution command is implemented then it should "just work" in a private message from what I remember. The only thing is if Countdown is channel limited like jeopardy you'll have to explicitly allow the private messages for just the `!solution` command.

**Comment by itpun** [comment]
@emmettu noted. I'm doing a check to make sure that the contestant is actually in the game channel as well before letting the submission go through

**Comment by onyiny-ang** [comment]
Closing this out 1 year out :+1:  Thanks again for the suggestions and implementation of this everyone :heart:
